/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jacsqdfurvdzwwfkbmkt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphY3NxZGZ1cnZkend3ZmtibWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MDk4MTcsImV4cCI6MjA4ODI4NTgxN30.KgUodBmvgHMdHWNx_I-1b8VYcetaZjrIEmoWVod4j-U"